<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.github.xezzon</groupId>
    <artifactId>zeroweb-service</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>
  <artifactId>zeroweb-service-open</artifactId>
  <packaging>jar</packaging>

  <name>${project.groupId}:${project.artifactId}</name>
  <description>开放平台服务</description>

  <properties>
    <http.port>9011</http.port>
    <grpc.port>9012</grpc.port>
    <management.port>9013</management.port>
    <mainClass>io.github.xezzon.zeroweb.ZerowebOpenApplication</mainClass>
  </properties>

  <dependencies>
    <dependency>
      <groupId>io.github.xezzon</groupId>
      <artifactId>zeroweb-open-sdk</artifactId>
      <version>1.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>com.auth0</groupId>
      <artifactId>java-jwt</artifactId>
      <version>4.5.0</version>
    </dependency>
  </dependencies>
</project>
