spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false
  datasource:
    hikari:
      leak-detection-threshold: 60000  # 测试环境检测连接泄露

logging:
  level:
    "[org.hibernate.orm.jdbc.bind]": trace
