spring:
  data:
    redis:
      url: redis://${REDIS_URL:localhost:6379}
      database: ${REDIS_DATABASE:0}
      timeout: 10s
      lettuce:
        pool:
          min-idle: 0
          max-idle: 10
          max-active: 200
          max-wait: -1ms
