spring:
  datasource:
    url: jdbc:mysql://${DB_URL:mysql:3306/zeroweb}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      "[hibernate.type.preferred_boolean_jdbc_type]": TINYINT
