spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false

logging:
  level:
    "[org.hibernate.orm.jdbc.bind]": trace

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
