"$schema": "https://json.schemastore.org/liquibase-3.2.json"

databaseChangeLog:
  - changeSet:
      id: "42"
      author: "xezzon"
      labels: "0.4"
      changes:
        - createTable:
            tableName: zeroweb_openapi
            remarks: "对外接口"
            columns:
              - column:
                  name: id
                  type: VARCHAR(64)
                  remarks: "对外接口标识"
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: code
                  type: VARCHAR(255)
                  remarks: "对外接口编码"
                  constraints:
                    unique: true
                    uniqueConstraintName: UK_o_code
                    nullable: false
              - column:
                  name: status
                  type: VARCHAR(255)
                  remarks: "接口发布状态"
                  constraints:
                    nullable: false

  - changeSet:
      id: "54"
      author: "xezzon"
      labels: "0.4"
      changes:
        - addColumn:
            tableName: zeroweb_openapi
            columns:
              - column:
                  name: destination
                  type: VARCHAR(2083)
                  remarks: "后端地址"
                  constraints:
                    nullable: false
              - column:
                  name: http_method
                  type: VARCHAR(16)
                  remarks: "接口请求的HTTP方法"
                  constraints:
                    nullable: false
