# Configuration file for Mega-Linter
# See all available variables at https://mega-linter.github.io/configuration.html and in linters documentation

ENABLE:
  - JAVA
  - PROTOBUF
  - EDITORCONFIG
  - COPYPASTE
  - REPOSITORY
ENABLE_LINTERS:
  - SQL_SQLFLUFF
  - SPELL_CSPELL
DISABLE_LINTERS:
  - REPOSITORY_KICS
  - REPOSITORY_GRYPE
  - REPOSITORY_DEVSKIM
DISABLE_ERRORS_LINTERS:
  - SPELL_CSPELL
  - COPYPASTE_JSCPD
  - REPOSITORY_TRIVY
  - JAVA_PMD
  - JAVA_CHECKSTYLE
  - REPOSITORY_CHECKOV

SARIF_REPORTER: true

PRE_COMMANDS:
  - command: curl https://raw.githubusercontent.com/checkstyle/checkstyle/refs/heads/master/src/main/resources/google_checks.xml > google_checks.xml
JAVA_PMD_POST_COMMANDS:
  - command: sed 's|file:///github/workspace/||' -i megalinter-reports/sarif/JAVA_PMD.sarif
    cwd: workspace

LINTER_RULES_PATH: .github/linters
JAVA_CHECKSTYLE_FILE_NAME: .github/linters/google_checks.xml
JAVA_PMD_CONFIG_FILE: .github/linters/java-pmd-rulesets.xml
SPELL_CSPELL_FILE_EXTENSIONS:
  - .java
  - .proto
