syntax = "proto3";

package io.github.xezzon.zeroweb.attachment;

import "google/protobuf/timestamp.proto";

option java_multiple_files = true;
option java_outer_classname = "AttachmentProto";
option java_package = "io.github.xezzon.zeroweb.attachment";

// 文件元数据
message FileMetadata {
  // 文件名
  string name = 1;
  // MIME 类型
  string type = 2;
  // 业务类型
  string biz_type = 3;
  // 业务ID
  string biz_id = 4;
}

// 文件上传请求
message FileUploadRequest {
  // 文件元数据
  FileMetadata metadata = 1;
  // 文件内容
  bytes chunk = 2;
}

// 文件上传响应
message FileUploadResponse {
  // 附件ID
  string id = 1;
}

// 查询附件列表请求
message QueryAttachmentListRequest {
  // 业务类型
  string biz_type = 1;
  // 业务ID
  string biz_id = 2;
}

// 附件状态
enum AttachmentStatus {
  // 正在上传
  UPLOADING = 0;
  // 上传完成
  DONE = 1;
}

message AttachmentItem {
  // 附件ID
  string id = 1;
  // 文件名
  string name = 2;
  // 文件摘要
  string checksum = 3;
  // 文件大小。单位：字节。
  uint64 size = 4;
  // MIME 类型
  string type = 5;
  // 附件状态
  AttachmentStatus status = 9;
  // 上传者
  optional string owner_id = 10;
  // 上传时间
  google.protobuf.Timestamp create_time = 11;
}

message AttachmentList {
  repeated AttachmentItem items = 1;
}

// 文件下载请求
message FileDownloadRequest {
  // 附件ID
  string id = 1;
}

// 文件下载响应
message FileDownloadResponse {
  // 文件元数据
  AttachmentItem metadata = 1;
  // 文件内容
  bytes chunk = 2;
}

// 附件管理服务
service Attachment {
  // 文件上传
  rpc uploadFile(stream FileUploadRequest) returns (FileUploadResponse);
  // 查询文件列表
  rpc queryAttachment(QueryAttachmentListRequest) returns (AttachmentList);
  // 文件下载
  rpc downloadFile(FileDownloadRequest) returns (stream FileDownloadResponse);
}
