services:
  ingress:
    image: traefik:3
    networks:
      - gateway
    ports:
      - "1081:80"
      - "8080"
    volumes:
      - $PWD/traefik/conf.d:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
  zeroweb-service-admin:
    image: ghcr.io/xezzon/zeroweb-service-admin:latest  # latest 为快照版本，正式版本请替换为版本号
    networks:
      - gateway
      - db
    environment:
      - ZEROWEB_ROOT_PASSWORD=zeroweb
      - DB_URL=postgresql:5432/zeroweb
      - DB_USERNAME=postgres_user
      - DB_PASSWORD=postgres_password
      - server.servlet.context-path=/admin
      - spring.grpc.client.channels.admin.address=localhost:10002
    volumes:
      - $PWD/pem:/app/resources/pem
    labels:
      - traefik.enable=true
    depends_on:
      - postgresql
  zeroweb-service-dev:
    image: ghcr.io/xezzon/zeroweb-service-dev:latest
    networks:
      - gateway
      - db
    environment:
      - DB_URL=postgresql:5432/zeroweb
      - DB_USERNAME=postgres_user
      - DB_PASSWORD=postgres_password
      - server.servlet.context-path=/dev
    labels:
      - traefik.enable=true
    depends_on:
      - postgresql
      - zeroweb-service-admin
  zeroweb-service-file:
    image: ghcr.io/xezzon/zeroweb-service-file:latest
    networks:
      - gateway
      - db
    environment:
      - DB_URL=postgresql:5432/zeroweb
      - DB_USERNAME=postgres_user
      - DB_PASSWORD=postgres_password
      - ZEROWEB_FILE_PROVIDER=FS
      - ZEROWEB_FS_BASEPATH=/srv/zeroweb/Uploads
      - server.servlet.context-path=/file
      - spring.grpc.client.channels.file.address=localhost:10022
    volumes:
      - $PWD/pem:/app/resources/pem
    labels:
      - traefik.enable=true
    depends_on:
      - postgresql
      - zeroweb-service-admin
  zeroweb-service-open:
    image: ghcr.io/xezzon/zeroweb-service-open:latest
    networks:
      - gateway
      - db
    environment:
      - DB_URL=postgresql:5432/zeroweb
      - DB_USERNAME=postgres_user
      - DB_PASSWORD=postgres_password
      - server.servlet.context-path=/open
    labels:
      - traefik.enable=true
    depends_on:
      - postgresql
      - zeroweb-service-admin
  postgresql:
    image: postgres:18
    networks:
      - db
    environment:
      - POSTGRES_DB=zeroweb
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw

networks:
  gateway:
    driver: bridge
  db:
    driver: bridge

volumes:
  postgres-data:
