/*
 * SPDX-FileCopyrightText: Copyright (C) 2025 xezzon
 * SPDX-License-Identifier: LGPL-3.0-or-later
 *
 * This file is part of ZeroWeb.
 *
 * ZeroWeb is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * ZeroWeb is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with ZeroWeb. If not, see <https://www.gnu.org/licenses/>.
 */

syntax = "proto3";

package io.github.xezzon.zeroweb.dict;

import "google/protobuf/empty.proto";

option java_multiple_files = true;
option java_outer_classname = "DictProto";
option java_package = "io.github.xezzon.zeroweb.dict";

// 字典请求
message DictReq {
  // 字典目
  optional string tag = 1;
}

// 字典响应
message DictResp {
  string id = 1;
  // 字典目
  string tag = 2;
  // 字典键
  string code = 3;
  // 字典值
  string label = 4;
  // 排序号
  int32 ordinal = 5;
  // 上级ID
  string parent_id = 6;
}

message DictListResp {
  repeated DictResp data = 1;
}

message DictImportReq {
  optional string tag = 1;
  string code = 2;
  optional string label = 3;
  int32 ordinal = 4;
}

message DictImportReqList {
  repeated DictImportReq data = 1;
}

// 字典相关的服务间接口
service Dict {
  // 根据字典目获取字典列表
  rpc GetDictListByTag(DictReq) returns (DictListResp);
  // 导入字典
  rpc ImportDict(DictImportReqList) returns (google.protobuf.Empty);
}
