name: release

permissions: read-all

on:
  release:
    types:
      - published

env:
  JAVA_DISTRIBUTION: 'temurin'
  JAVA_VERSION: '25'

jobs:
  set-version:
    runs-on: ubuntu-24.04
    outputs:
      project_version: ${{ steps.set_version.outputs.project_version }}
      image_version: ${{ steps.set_version.outputs.image_version }}
    steps:
      - id: set_version
        env:
          PROJECT_VERSION: ${{ github.ref_name }}
          IMAGE_VERSION: ${{ github.event.release.prerelease && 'latest' || github.ref_name }}
        run: |
          echo "project_version=${PROJECT_VERSION}" >> $GITHUB_OUTPUT
          echo "image_version=${IMAGE_VERSION}" >> $GITHUB_OUTPUT
  publish-sdk:
    needs: set-version
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Apache Maven Central
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      - name: Set SDK Version
        run: mvn -B versions:set -D newVersion=${{ needs.set-version.outputs.project_version }}
      - name: Publish Java package
        run: mvn -B deploy -P release -D skipTests=true -T 1C
        env:
          MAVEN_USERNAME: ${{ vars.MAVEN_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
  publish-service:
    needs: set-version
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      attestations: write
    env:
      DOCKER_HOST: ghcr.io
    steps:
      - uses: actions/checkout@v4
      - name: Set up Apache Maven Central
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'
          server-id: ${{ env.DOCKER_HOST }}
          server-username: DOCKER_USERNAME
          server-password: DOCKER_TOKEN
      - name: Publish Docker image
        run: >
          mvn -B deploy 
          -P docker 
          -D skipTests=true 
          -D image.version=${{ needs.set-version.outputs.image_version }}
          -T 1C
        env:
          DOCKER_REGISTRY: ${{ env.DOCKER_HOST }}/${{ github.repository_owner }}
          DOCKER_USERNAME: ${{ github.repository_owner }}
          DOCKER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  report:
    needs: set-version
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: ./.github/workflows/report.yml
    with:
      version: ${{ needs.set-version.outputs.project_version }}
