name: release

permissions: read-all

on:
  release:
    types:
      - published

env:
  DOCKER_HOST: ghcr.io

jobs:
  publish-proto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Apache Maven Central
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      - name: Set Version
        run: mvn -B versions:set -DnewVersion=$GITHUB_REF_NAME
      - name: Publish Java package
        run: mvn -B deploy -P release -DskipTests=true
        env:
          MAVEN_USERNAME: ${{ vars.MAVEN_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
  publish-service:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Apache Maven Central
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          server-id: ${{ env.DOCKER_HOST }}
          server-username: DOCKER_USERNAME
          server-password: DOCKER_TOKEN
      - name: Set Version
        run: mvn -B versions:set -DnewVersion=$GITHUB_REF_NAME
      - name: Build the project
        run: mvn -B install
      - name: Publish Docker image
        run: mvn -B jib:build -P docker -rf zeroweb-service
        env:
          DOCKER_REGISTRY: ${{ env.DOCKER_HOST }}/${{ github.repository_owner }}
          DOCKER_USERNAME: ${{ github.repository_owner }}
          DOCKER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  report:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Apache Maven Central
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Set Version
        run: mvn -B versions:set -DnewVersion=$GITHUB_REF_NAME
      - name: Generate the report
        run: mvn -B site site:stage -P report
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'target/staging'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
