# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Test

permissions: read-all

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  unit-test:
    strategy:
      fail-fast: false
      matrix:
        db_type: [ "postgresql", "mysql" ]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'
      - name: Cache SonarCloud packages
        uses: actions/cache@v5
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v5
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Unit test and installation for SDK
        run: >
          mvn -B clean install
          -pl zeroweb-spring-boot-starter,zeroweb-open-sdk -am
          -T 1C
      - name: Unit test for services
        working-directory: zeroweb-service
        run: >
          mvn -B test
          -D db.type=${{ matrix.db_type }}
          -T 1C
      - name: Integration test
        run: >
          mvn -B verify
          -D skipTests=true -D skipITs=false
          -T 1C
      - name: Analyze code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -D sonar.projectKey=xezzon_zeroweb-spring
